In [3]:
import numpy as np

# Question 1

In [7]:
a = np.arange(21)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# Question 2

In [9]:
b = a[::2]
print(b)

[ 0  2  4  6  8 10 12 14 16 18 20]


# Question 3

In [14]:
c = a[::3]
print(c)

[ 0  3  6  9 12 15 18]
